apiVersion: rabbit-stalker.docplanner.com/v1alpha1
kind: WorkloadAction
metadata:
  labels:
    app.kubernetes.io/name: workloadaction
    app.kubernetes.io/instance: workloadaction-sample
    app.kubernetes.io/part-of: rabbit-stalker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rabbit-stalker
  name: workloadaction-sample
spec:
  synchronization:
    time: 10s

  # Configuration
  rabbitConnection:
    url: "https://your-server.rmq.cloudamqp.com"
    vhost: "shared"
    queue: "your-queue-here"

    # Credentials are optional.
    # If set, both are required
    credentials:
      username:
        secretRef:
          name: testing-secret
          key: RABBITMQ_USERNAME
      password:
        secretRef:
          name: testing-secret
          key: RABBITMQ_PASSWORD

  # Additional sources to get information from.
  # This sources can be used on condition.value
  additionalSources:
    - apiVersion: apps/v1
      kind: Deployment
      name: testing-workload
      namespace: default

  # Condition under the action is executed.
  # The 'key' field admits dot notation, and it's covered by gjson
  # Ref: https://github.com/tidwall/gjson
  condition:
    key: |-
      consumer_details.#(channel_details.node==rabbit@fancy-monk-sample-01).channel_details.node

    # Additional sources can be used here to craft complex values using the following pattern:
    # [index]{{ gjson }}
    value: |-
      [0]{{ metadata.annotations.node }}

  # Action to do with the workload when the condition is met
  action: "restart"

  # The workload affected by the action
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testing-workload
    namespace: default

