apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rabbit-stalker
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: rabbit-stalker
  name: rabbit-stalker-leader-election-rolebinding
  namespace: rabbit-stalker-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbit-stalker-leader-election-role
subjects:
- kind: ServiceAccount
  name: rabbit-stalker-controller-manager
  namespace: rabbit-stalker-system
